In [74]:
import math
import pandas as pd
from operator import itemgetter
from google.colab import files
import io
import numpy as py
import random
K = 2

In [4]:
upload = files.upload()

Saving KMeans.csv to KMeans.csv


In [5]:
upload

{'KMeans.csv': b'X,Y\r\n1,2\r\n2,3\r\n2,3\r\n1,4\r\n5,1\r\n4,7\r\n4,2\r\n3,3\r\n2,4\r\n'}

In [8]:
data = pd.read_csv(io.BytesIO(upload['KMeans.csv']))

In [9]:
data

X  Y
0  1  2
1  2  3
2  2  3
3  1  4
4  5  1
5  4  7
6  4  2
7  3  3
8  2  4

In [11]:
dataku = pd.DataFrame(data)

In [12]:
dataku

X  Y
0  1  2
1  2  3
2  2  3
3  1  4
4  5  1
5  4  7
6  4  2
7  3  3
8  2  4

In [20]:
dataku=pd.DataFrame(data).to_numpy()

In [21]:
dataku

array([[1, 2],
       [2, 3],
       [2, 3],
       [1, 4],
       [5, 1],
       [4, 7],
       [4, 2],
       [3, 3],
       [2, 4]])

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [112]:
center=py.zeros((K,dataku.shape[1]))
i = 0
while (i <=1):
    j=0
    while (j<=1):
        center[i][j]=random.randrange(dataku.min(),dataku.max())
        j+=1
    i+=1
center


array([[5., 1.],
       [2., 3.]])

In [111]:
distance=py.ones((dataku.shape[0],K))


In [113]:
Clustering=py.ones(dataku.shape[0]) #Menentukan masuk ke cluster mana tiap data
Clustering=Clustering.astype(int)
Clustering_sebelumnya=py.ones(dataku.shape[0]) #Menentukan masuk ke cluster mana tiap data
Clustering_sebelumnya=Clustering_sebelumnya.astype(int)
flag=0

while(not flag):

  ###Untuk menentukan apakah cluster sebelumnya sama atau tidak

  i=0
  while (i<dataku.shape[0]):
    Clustering_sebelumnya[i]=Clustering[i]
    i+=1

  ###Untuk melakukan penjarakan terhadap Center

  i=0
  while i<dataku.shape[0]:
    j=0
    while j<K:
      distance[i][j]=math.sqrt((dataku[i][0]-center[j][0])**2 + (dataku[i][1]-center[j][1])**2)
      j+=1
    i+=1

  ###Tampilkan jarak
  print("\n--------- Distance --------\n")
  print(distance)

  ###Menentukan masuk ke cluster tiap data

  i=0
  while (i<dataku.shape[0]):
    if (distance[i][0]<=distance[i][1]):
      Clustering[i]=0
    else:
      Clustering[i]=1
    i+=1
  
  print("\n -- Clustering --")
  print(Clustering)
  print("\n -- Clustering Sebelumnya --")
  print(Clustering_sebelumnya)
  ###Membuat center baru
  center=py.zeros((K,dataku.shape[1]))
  n_cluster1 = 0
  n_cluster2 = 0
  j=0
  while (j<data.shape[0]):
    if (Clustering[j] == 0):
      center[0][0] += dataku[j][0]
      center[0][1] += dataku[j][1]
      n_cluster1 +=1
    else:
      center[1][0] += dataku[j][0]
      center[1][1] += dataku[j][1]
      n_cluster2 +=1
    j+=1
  center[0][0] /= n_cluster1
  center[0][1] /= n_cluster1
  center[1][0] /= n_cluster2
  center[1][1] /= n_cluster2
  print("\n ---- Center ----")
  print(center)
  #Jika cluster sama dengan sebelumnya maka hentikan perulangan

  i=0
  flag=1
  while (i<dataku.shape[0]):
    if(Clustering_sebelumnya[i] != Clustering[i]):
      flag = 0
      break
    print(i)
    print("-----")
    i+=1
print("\nFinish....!!!")


--------- Distance --------

[[4.12310563 1.41421356]
 [3.60555128 0.        ]
 [3.60555128 0.        ]
 [5.         1.41421356]
 [0.         3.60555128]
 [6.08276253 4.47213595]
 [1.41421356 2.23606798]
 [2.82842712 1.        ]
 [4.24264069 1.        ]]

 -- Clustering --
[1 1 1 1 0 1 0 1 1]

 -- Clustering Sebelumnya --
[1 1 1 1 1 1 1 1 1]

 ---- Center ----
[[4.5        1.5       ]
 [2.14285714 3.71428571]]
0
-----
1
-----
2
-----
3
-----

--------- Distance --------

[[3.53553391 2.06031501]
 [2.91547595 0.72843136]
 [2.91547595 0.72843136]
 [4.30116263 1.17803018]
 [0.70710678 3.94088978]
 [5.52268051 3.77424138]
 [0.70710678 2.52740086]
 [2.12132034 1.11574995]
 [3.53553391 0.31943828]]

 -- Clustering --
[1 1 1 1 0 1 0 1 1]

 -- Clustering Sebelumnya --
[1 1 1 1 0 1 0 1 1]

 ---- Center ----
[[4.5        1.5       ]
 [2.14285714 3.71428571]]
0
-----
1
-----
2
-----
3
-----
4
-----
5
-----
6
-----
7
-----
8
-----

Finish....!!!
