In [32]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
upload = files.upload()

import io
predikat = pd.read_csv(io.BytesIO(upload['dataset KNN.csv']))
predikat;

Saving dataset KNN.csv to dataset KNN (1).csv


In [ ]:
predikat.head()

IPK  Keikutsertaan Pelatihan  Prestasi  Forum Ilmiah  Kegiatan Organisasi  \
0  3.13                        6         1             1                    3   
1  3.12                        6         0             1                    1   
2  3.29                        6         2             3                    3   
3  3.10                        2         0             6                    2   
4  3.12                        3         3             4                    2   

   Lulus Cepat  
0            0  
1            1  
2            1  
3            1  
4            0

In [ ]:
predikat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   IPK                      33 non-null     float64
 1   Keikutsertaan Pelatihan  33 non-null     int64  
 2   Prestasi                 33 non-null     int64  
 3   Forum Ilmiah             33 non-null     int64  
 4   Kegiatan Organisasi      33 non-null     int64  
 5   Lulus Cepat              33 non-null     int64  
dtypes: float64(1), int64(5)
memory usage: 1.7 KB


In [ ]:
#menentukan variable independen
x = predikat.drop(["Lulus Cepat"], axis = 1)
x.head()

IPK  Keikutsertaan Pelatihan  Prestasi  Forum Ilmiah  Kegiatan Organisasi
0  3.13                        6         1             1                    3
1  3.12                        6         0             1                    1
2  3.29                        6         2             3                    3
3  3.10                        2         0             6                    2
4  3.12                        3         3             4                    2

In [ ]:
y = predikat['Lulus Cepat']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Lulus Cepat, dtype: int64

In [ ]:
#import paket
from sklearn.model_selection import train_test_split

In [ ]:
#membagi data untuk pelatihan dan pengujian
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.20)

In [ ]:
#mengubah skala data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
#import KNN dari sklearn
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4)

In [ ]:
#aktifkan knn
knn.fit(x_train, y_train)


KNeighborsClassifier(n_neighbors=4)

In [ ]:
y_pred = knn.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0])

In [ ]:
knn.predict_proba(x_test)

array([[0.25, 0.75],
       [0.25, 0.75],
       [0.75, 0.25],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.75, 0.25]])

In [ ]:
#import paket untuk hitung akurasi prediksi
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[4 1]
 [0 2]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.80      0.89         5
           1       0.67      1.00      0.80         2

    accuracy                           0.86         7
   macro avg       0.83      0.90      0.84         7
weighted avg       0.90      0.86      0.86         7

