In [36]:
import math
import pandas as pd
from operator import itemgetter
from google.colab import files
import io
import numpy as py
import random
import heapq
K = 3

In [3]:
upload = files.upload()

Saving KNN.csv to KNN.csv


In [ ]:
upload

{'KNN.csv': b'X,Y\r\n1,2\r\n2,3\r\n2,3\r\n1,4\r\n5,1\r\n4,7\r\n4,2\r\n3,3\r\n2,4\r\n'}

In [4]:
data = pd.read_csv(io.BytesIO(upload['KNN.csv']))

In [18]:
data['Y'].nlargest(2)

5    7
3    4
Name: Y, dtype: int64

In [6]:
dataku = pd.DataFrame(data)

In [7]:
dataku=pd.DataFrame(data).to_numpy()
dataku

array([[1, 2],
       [2, 3],
       [2, 3],
       [1, 4],
       [5, 1],
       [4, 7],
       [4, 2],
       [3, 3],
       [2, 4]])

In [92]:
klasifikasi = (py.zeros((dataku.shape[0])))
klasifikasi=klasifikasi.astype(int)
klasifikasi[5]=1
klasifikasi[3]=1
klasifikasi[6]=1
klasifikasi


array([0, 0, 0, 1, 0, 1, 1, 0, 0])

In [9]:
fileknn=files.upload()

Saving Test.csv to Test.csv


In [10]:
test = pd.read_csv(io.BytesIO(fileknn['Test.csv']))
test

X  Y
0  1  2
1  3  1
2  3  3

In [11]:
test=test.to_numpy()

In [12]:
test

array([[1, 2],
       [3, 1],
       [3, 3]])

In [81]:
n_klass=py.zeros(test[0])
klass=py.zeros(test.shape[0])
klass=klass.astype(int)
klass

array([0, 0, 0])

In [14]:
distance=py.zeros((dataku.shape[0],test.shape[0]))
distance

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
i=0
while i<dataku.shape[0]:
  j=0
  while (j<test.shape[0]):
    distance[i][j] = math.sqrt((test[j][0]-dataku[i][0])**2+(test[j][1]-dataku[i][1])**2)
    j+=1
  i+=1

print("\n--- Distance Setiap Test ---\n") 
print(distance)


--- Distance Setiap Test ---

[[0.         2.23606798 2.23606798]
 [1.41421356 2.23606798 1.        ]
 [1.41421356 2.23606798 1.        ]
 [2.         3.60555128 2.23606798]
 [4.12310563 2.         2.82842712]
 [5.83095189 6.08276253 4.12310563]
 [3.         1.41421356 1.41421356]
 [2.23606798 2.         0.        ]
 [2.23606798 3.16227766 1.41421356]]


In [101]:
klass=py.zeros(test.shape[0])
klass=klass.astype(int)

distance_df=pd.DataFrame(distance, columns = ['1','2','3'])
largest=distance_df.apply(lambda s: pd.Series(s.nlargest(K).index))
largest_py=largest.to_numpy()

print("\n---- Tampilkan Index",K," Terbesar Tiap Kolom----")
print(largest_py)
i=0
while i<test.shape[0]:
  j=0
  while j<K:
    if (klasifikasi[largest_py[j][i]]==1):
      klass[i]+=1
    j+=1
  i+=1
print("\nJumlah K-terdekat")
print(klass)
i=0
while i<klass.shape[0]:
  if (klass[i]<K/2):
    print("Test ke-",i," termasuk klasifikasi 0")
  else:
    print("Test ke-",i," termasuk klasifikasi 1")
  i+=1


---- Tampilkan Index 3  Terbesar Tiap Kolom----
[[5 5 5]
 [4 3 4]
 [6 8 0]]

Jumlah K-terdekat
[2 2 1]
Test ke- 0  termasuk klasifikasi 1
Test ke- 1  termasuk klasifikasi 1
Test ke- 2  termasuk klasifikasi 0
